[workspace]

resolver = "1"
members = [
    "calc",
    "catp",
    "comzip",
    "csv_json",
    "decom",
    "echop",
    "encode",
    "gentype", "headp",
    "hello",
    "merge_img", "mini-http",
    "minigrep",
    "newsletter",
    "parse_tab", "rditoki",
    "remove_uid",
    "rename_ts"
]
