[package]
name = "cesm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.6", features = ["derive"] }
glob = "0.3"
regex = "1.10"
