[package]
name = "epo"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities"]
description = "Handy epoch converter."

[dependencies]
chrono = "0.4.35"
chrono-tz = "0.8.6"
once_cell = "1.19.0"
Boa = "0.13.1"
boa_engine = "0.18.0"
