# Set default environment variables
POSTGRES_USER       := "postgres"
POSTGRES_PASSWORD   := "password"
POSTGRES_DB         := "newsletter"
POSTGRES_PORT       := "5432"
DATABASE_URL        := "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}"

# Define tasks

init_db:
	docker run \
		-e POSTGRES_USER=$(POSTGRES_USER) \
		-e POSTGRES_PASSWORD=$(POSTGRES_PASSWORD) \
		-e POSTGRES_DB=$(POSTGRES_DB) \
		-p $(POSTGRES_PORT):5432 \
		-d postgres \
		postgres -N 1000

create_db:
	sqlx database create

migrate_db:
	sqlx migrate add create_subscriptions_table

migrate_run:
	sqlx migrate run
