[package]
name = "del_branches"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.2"
thiserror = "1.0.58"
crossterm = "0.27.0"
chrono = "0.4.35"