name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  all-jobs:
    if: always()
    name: all-jobs
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'

  check:
    name: Check project clippy, fmt, tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Get rustfmt
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Run fmt
      run: cargo fmt -- --check
    - name: Run clippy
      run: cargo clippy --all-targets
    - name: Run tests
      run: cargo test --verbose
